### ISSUE TITLE
Kodi flatpak crashes on startup

### ISSUE THREAD

**Issue by sjuk** [flathub/tv.kodi.Kodi#149] opened 2022-01-23 12:04 UTC
Hello Everybody,

Kodi (19.**2**-Matrix) flatpak from [https://flathub.org/apps/details/tv.kodi.Kodi](https://flathub.org/apps/details/tv.kodi.Kodi) crashes on startup.
```
$ flatpak run tv.kodi.Kodi
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
/app/bin/kodi: line 187:     7 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS
```
Kodi (19.**3**-Matrix) debian package from official Team Kodi PPA works fine.
[https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux](https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux)
```
$ kodi
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
```
Does anyone have got an idea what’s wrong with the flatpak?

Thanks in advance & best regards
sjuk
```
$ neofetch 
            .-/+oossssoo+/-.               sjuk@asterix 
        `:+ssssssssssssssssss+:`           ------------ 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: B365M H 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-96-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 31 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2285 (dpkg), 12 (flatpak), 6 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i3-9100 (4) @ 4.200GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel 8th Gen Core Processor Gaussian Mixture Model 
      -+sssssssssssssssssyyyssss+-         Memory: 2992MiB / 15881MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

**Comment by wsnipex** [comment] 2022-01-23 12:25
duplicate of #147

**Closed by wsnipex** 2022-01-23 12:25 UTC
Labels: duplicate
