### ISSUE TITLE
Kodi Version Number

### ISSUE THREAD

**Issue by gj207** [flathub/tv.kodi.Kodi#129] opened 2021-11-20 09:03 UTC
Only a minor issue: If you run the latest flathub version of the tv.kodi.Kodi flatpak, the start-up screen shows version 19.3-Matrix. However, the command "flatpak info tv.kodi.Kodi" still shows the previous version 19.2-Matrix.

**Comment by razzeee** [comment] 2021-12-21 17:36
Yes, we're using the appstream from upstream now and as this is a new process, we failed to increase that version unfortunately. Closing, as this needs to be handled upstream.

**Closed by razzeee** 2021-12-21 17:36 UTC

**Comment by sjuk** [comment] 2022-01-24 15:29
I wonder why this issue is set to closed, but the version number is still wrong.
```
$ flatpak list
Name                          Application ID                                Version              Zweig           Installation
Discord                       com.discordapp.Discord                        0.0.16               stable          system
Freedesktop Platform          org.freedesktop.Platform                      21.08.9              21.08           system
Mesa                          org.freedesktop.Platform.GL.default           21.3.3               21.08           system
Intel                         org.freedesktop.Platform.VAAPI.Intel                               21.08           system
openh264                      org.freedesktop.Platform.openh264             2.1.0                2.0             system
Yaru Gtk Theme                org.gtk.Gtk3theme.Yaru                                             3.22            system
Signal Desktop                org.signal.Signal                             5.29.0               stable          system
Kodi                          tv.kodi.Kodi                                  19.2-Matrix          stable          system
```
```
$ flatpak run tv.kodi.Kodi --version
19.3 (19.3.0) Git:20220123-nogitfound Media Center Kodi
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv
```

**Comment by razzeee** [comment] 2022-01-24 15:52
We won't be patching the appstream file and it will be gone with the next kodi version anyway. As long as nobody messes up the release process.

**Comment by razzeee** [comment] 2022-01-24 16:33
No, it shouldn't be gone, we just recently moved it upstream. It just needs to be updated as part of the release process.

**Comment by sjuk** [comment] 2022-01-24 17:28
> No, it shouldn't be gone, we just recently moved it upstream. It just needs to be updated as part of the release process.
Perhaps it's difficult for me as an outsider to be able to follow you. I will try to fill in the missing information to getting closer.

Replacing it by what I guess you want to say.
No, **the metadata file with the version** shouldn't be gone. We just recently moved the file upstream.
**The metadata file containing the version** just needs to be updated as part of the release process.

That said. The issue will be open until the metadata file containing the version was updated as part of the release process of kodi or of tv.kodi.kodi flatpak? Or both?

**Comment by razzeee** [comment] 2022-01-24 22:30
Sure, we could keep the issue open, but it's out of our hands/not actionable. However you could try to contribute to upstream and add some checks to their pipelines. OBS has some nice things that you could learn from.

**Comment by sjuk** [comment] 2022-01-25 18:11
> Sure, we could keep the issue open, but it's out of our hands/not actionable.
I'm not sure that this is 100% true.
I agree with you that it's out of your hands/not actionable to update the metadata file in kodi code.
But you should be able to switch the currently implemented procedure for updating the kodi version number in tv.kodi.Kodi code. Obviously the currently implemented way is not reliable. I personally would recommend you to use `kodi-bin --version` to determine the current version of kodi packaged in tv.kodi.Kodi.

**Comment by sjuk** [comment] 2022-01-25 18:19
> However you could try to contribute to upstream and add some checks to their pipelines. OBS has some nice things that you could learn from.

I guess it's one of your hobbies: Talking in riddles. :hand_over_mouth:
Searching the web [https://duckduckgo.com/?t=ffab&q=obs&ia=web](https://duckduckgo.com/?t=ffab&q=obs&ia=web) leads me to [Open Broadcaster Software | OBS](https://obsproject.com/). But coming from the context of our conversation that can't be true. 
Despite from that I love to learn something new. This is one of my favourite hobbies. :wink:

**Comment by razzeee** [comment] 2022-01-25 19:18
Sorry, was replying by phone in a drive by style :)

OBS has some sanity checks in their build pipeline for flathub, kodi should eventually get the same if not even more/different sanity checks.
https://github.com/obsproject/obs-studio/pull/5569/files#diff-0204cdf2cea745a516b9aa6ee61205f02d0738627a1ae7a74c7800865c3a8115R84

**Comment by sjuk** [comment] 2022-01-25 19:41
> Sorry, was replying by phone in a drive by style :)
> 
> OBS has some sanity checks in their build pipeline for flathub, kodi should eventually get the same if not even more/different sanity checks. https://github.com/obsproject/obs-studio/pull/5569/files#diff-0204cdf2cea745a516b9aa6ee61205f02d0738627a1ae7a74c7800865c3a8115R84

Don't mind. I still don't get the point. But I guess we are drifting away from the discussion about the issue and how to solve it for flatpak tv.kodi.Kodi code (not for kodi code). Coming back to the beginning of the discussion...

> Sure, we could keep the issue open, but it's out of our hands/not actionable.

I'm not sure if this is 100% true.
I agree with you that it's out of your hands/not actionable to update the metadata file in kodi code.
But you should be able to switch the currently implemented procedure for updating the kodi version number in tv.kodi.Kodi code. Obviously the currently implemented way is not reliable. I personally would recommend to use kodi-bin --version to determine the current version of kodi packaged in tv.kodi.Kodi.

**Comment by Erick555** [comment] 2022-01-25 23:38
> But you should be able to switch the currently implemented procedure for updating the kodi version number in tv.kodi.Kodi code. Obviously the currently implemented way is not reliable.

The thing is there is no _procedure for updating the kodi version number in tv.kodi.Kodi code_ at all because it was moved to upstream kodi code and moving it back permanently is unwanted when current problem is transitory.

Kodi flatpak could fix the version themselves and undo it for next release but it may not worth the effort to do so.

**Comment by gj207** [comment] 2022-01-26 06:02
It is a truism among software developers: If it is an "effort" to change 
or update a build version number, either the build process needs to be 
revised entirely or the people doing the build are simply unwilling to 
change that number! 🙁

Am 26.01.22 um 00:38 schrieb Erick555:

**Comment by sjuk** [comment] 2022-01-26 07:16
> > But you should be able to switch the currently implemented procedure for updating the kodi version number in tv.kodi.Kodi code. Obviously the currently implemented way is not reliable.
> 
> The thing is there is no _procedure for updating the kodi version number in tv.kodi.Kodi code_ at all because it was moved to upstream kodi code and moving it back permanently is unwanted when current problem is transitory.
> 
> > I agree with you that it's out of your hands/not actionable to update the metadata file in kodi code.
> 
> It is - kodi flatpak could patch the version themselves and undo it for next release but I guess it was decided not worth the effort.

Many thanks. Now I see much clearer where the root cause for the issue lies. It was a design decision of people that was not aware of Murphy's Law.

Regarding the effort: It depends on what goal you want to achieve. Build automation is a good goal. And you can achieve it also when switching the version number identification to flatpak.
From a user perspective it would be a no-brainer. If I see flatpak only Kodi 19.2 providing, I would stick to the Debian package. And even if you say that's only a bug in the metadata the user could say: Is there anything else wrong with that package? They did not even set the version number right.
And another point is. You don't have any assurance that the version number in Kodi code will be set right.

Don't get me wrong. I only want you to consider to choose the best option for your flatpak.
