### ISSUE TITLE
ARM version missing on flathub

### ISSUE THREAD

**Issue by cintema** [flathub/tv.kodi.Kodi#83] opened 2020-04-19 16:22 UTC
I already complained at the Kodi guys but they declined to support flatpak, unfortunately.
https://github.com/xbmc/xbmc/issues/17700

Since an ARM release exists (e.g. for raspi) I guess it should be possible to repack it into a flatpak package.
Thank you.

**Comment by cintema** [comment] 2020-04-23 09:20
I have examined the content of this repo and I did not completly understand how the automatic flathub build process works at all.
However, I do understand that this repo does mainly contain build scripts, and the ARM release of Kodi is intentionally excluded. Why is that? Does the ARM release not build? Can I contribute to make it work?
Thank you in advance!

**Comment by wsnipex** [comment] 2020-04-23 09:31
the ARM world for hardware video decoding very fragmented, so there is no kodi ARM build that works on all platforms. You'd basically have to provide a specific build for all the major vendors(e.g. raspberry pi2/3/4, rockchip, amlogic, odroid....)
Once most major vendors _and kodi_ support GBM/V4L2, this could be revisited

**Comment by hfiguiere** [comment] 2020-07-07 00:09
Duplicate of #35?

**Comment by Marko10-000** [comment] 2020-07-25 00:13
Duplicate.

**Closed by Marko10-000** 2020-07-25 00:13 UTC
Labels: duplicate

**Comment by gj207** [comment] 2021-11-20 10:04
>
Since I'm using a Fedora 35 distribution with downstream Raspberry-Pi kernel (see https://rpmfusion.org/Howto/RaspberryPi), I would also appreciate if there was a flatpak optimized for Raspbery Pi 4 aarch64.
So for the time being, I have to live with a snap package (see https://snapcraft.io/kodi-pi-standalone) to make use of the hardware video decoding features provided by the Raspi Downtream kernel...

**Comment by hfiguiere** [comment] 2021-11-20 15:53
See #35

**Comment by hfiguiere** [comment] 2021-11-21 03:09
@gj207 you can try the test build in pr #130 (aarch64)

**Comment by gj207** [comment] 2021-11-21 13:18
> @gj207 you can try the test build in pr #130 (aarch64)

Hi Hubert, thank you very much for this kodi testing flatpak!
I have tested it on my Raspi4 with Fedora 35 aarch64 running the Raspberry Pi downtream kernel. Unfortunately I did not get hardware accelerated video decoding working with that flatpak. I have tried two different OS copnfigurations:
First set of options in /boot/config.txt (default settings as being provided by the images at  https://rpmfusion.org/Howto/RaspberryPi):
dtoverlay=vc4-fkms-v3d
gpu_mem=320
Second set of options (as e.g. used by the LibreELEC 10.0.1 distribution):
dtoverlay=vc4-kms-v3d,cma-512
dtoverlay=rpivid-v4l2
dtoverlay=
disable_fw_kms_setup=1

Have you got HW accelerated video decoding working with that flatpak on a Raspberry pi 4? If yes, please let me know more details about your OS configuration!

**Comment by hfiguiere** [comment] 2021-11-22 02:08
as I mentionned in the PR (hence the Draft status) I haven't tested it yet. just triggered a build. I couldn't even finish the build locally.

**Comment by gj207** [comment] 2021-12-09 06:09
Have you tested it in the meantime?

As already mentioned HW accelerated video decoding does not work with 
that flatpak on a Raspberry Pi 4 with the OS configuration described 
above. So maybe other testers could give some hints..

Am 22.11.21 um 03:08 schrieb Hubert Figuière:
