### ISSUE TITLE
Missing nmblookup dependency

### ISSUE THREAD

**Issue by 0x20Man** [flathub/tv.kodi.Kodi#71] opened 2019-10-19 09:37 UTC
I don't use Samba and I don't experience other issues, but when launching Kodi from a terminal there's a message:

    sh: nmblookup: command not found

Under */var/lib/flatpak/.../files/sbin* I can only find nmbd and smbd commands.

**Comment by nicrame** [comment] 2020-07-01 11:00
I can confirm the same on latest Kodi flatpak.
![Desktop-love NAS-2020-07-01-13-00](https://user-images.githubusercontent.com/5872054/86236764-e637dd80-bb9a-11ea-9bdd-df0097441965.jpg)

**Comment by Marko10-000** [comment] 2020-07-01 22:02
Can't reproduce. Which OS do you use?

**Comment by nicrame** [comment] 2020-07-01 23:41
I'm at CentOS 8, minimal install.

**Comment by nicrame** [comment] 2020-07-19 20:39
To be more specific, this error occurs only when You try to add folder with multimedia files, or just browsing it (thru Settings\File manager\Add source), and when You click Browse, You will then click on Windows network (SMB).
The reason is lack of nmblookup that is used for that.

**Comment by Erick555** [comment] 2020-07-20 11:23
Is it only about the printed message or missing functionality too? Does browsing those files work?

**Comment by nicrame** [comment] 2020-07-20 11:43
For me it do not work (it do not show folders from Windows computers, and also do not detect Samba share on the same CentOS computer).
Screenshot from browsing SMB shares on KODI:
![Desktop-love NAS-2020-07-20-13-32](https://user-images.githubusercontent.com/5872054/87934164-d111e880-ca8e-11ea-8db8-ac4248dfb18e.png)
And here same pc, same user, just xterm terminal:
![Desktop-love NAS-2020-07-20-13-40](https://user-images.githubusercontent.com/5872054/87934250-fbfc3c80-ca8e-11ea-9d10-75a7b07a347b.png)

**Comment by vilmasvensson** [comment] 2021-03-15 20:02
Does this issue still persist now that #103 has been merged?

**Comment by nicrame** [comment] 2021-03-15 20:19
On flathub there is still old version. I will check https://dl.flathub.org/build-repo/40223/tv.kodi.Kodi.flatpakref and let You know.

**Comment by nicrame** [comment] 2021-03-15 20:55
1: Browsing thru Settings\File manager\Add source --> Browse --> Windows network (SMB) give same result (nothing is shown, even samba is working on the same host, and there are other computers around):

![Desktop-Love-NAS-2021-03-15-21-37](https://user-images.githubusercontent.com/5872054/111218928-b40ac680-85d7-11eb-96cc-bad7ba84236b.png)


2: HDMI/CEC is working now. I can control Kodi with TV remote again.
3: Web access/control is working again.

`# flatpak info tv.kodi.Kodi//test

Kodi - Media center

             Identyfikator: tv.kodi.Kodi
               Odniesienie: app/tv.kodi.Kodi/x86_64/test
              Architektura: x86_64
                     Gałąź: test
                    Wersja: 19.0-Matrix
                  Licencja: GPL-2.0-only GPL-2.0-or-later LGPL-2.1-or-later MIT BSD-3-Clause BSD-4-Clause
               Pochodzenie: kodi-origin
                  Kolekcja: org.flathub.Stable.Build40223
                Instalacja: system
             Zainstalowano: 354,8 MB
     Środowisko wykonawcze: org.freedesktop.Platform/x86_64/20.08
Środowisko programistyczne: org.freedesktop.Sdk/x86_64/20.08

             Zatwierdzenie: 55595bfbb350f7ce67f7f5424cdf482a5ca3d8d782f89370e9cc6f8f24f221b6
                     Temat: Fix perl and samba (ac996893)
                      Data: 2021-03-15 14:25:28 +0000`

Also. When "exit" from kodi it freeze for about minute or two and show this:
```
$ flatpak run tv.kodi.Kodi
EXIT using menu...
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
sh: linia 1: nmblookup: nie znaleziono polecenia
sh: linia 1: nmblookup: nie znaleziono polecenia
sh: linia 1: nmblookup: nie znaleziono polecenia
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
StartSession: hostname: Love-NAS
```
So it says there is no nmblookup.
Sometimes those "SartSession: hiostname: Love-NAS is like 50 lines!

So yes, this issue is still there.

**Comment by nicrame** [comment] 2021-03-16 12:55
Yes. They are there now.

**Comment by razzeee** [comment] 2023-01-29 13:02
I don't see this happening anymore with the current builds, can anyone confirm?

**Comment by nicrame** [comment] 2023-01-29 16:08
Today i updates and i also do not see that problem anymore! Finally, after just 4 years! :D

**Closed** 2023-01-29 16:35 UTC
